"""add model consent and pseudonyms

Revision ID: f36e6e8a91b3
Revises: fe52577cd05f
Create Date: 2026-07-14 15:19:00.079248
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f36e6e8a91b3'
down_revision: Union[str, None] = 'fe52577cd05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_pseudonyms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('entity_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_length', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('pseudonym', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'entity_fingerprint', name='uq_case_pseudonym_fingerprint'),
    sa.UniqueConstraint('case_id', 'pseudonym', name='uq_case_pseudonym_label')
    )
    op.create_index(op.f('ix_case_pseudonyms_case_id'), 'case_pseudonyms', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_pseudonyms_tenant_id'), 'case_pseudonyms', ['tenant_id'], unique=False)
    op.create_table('model_data_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('purposes', sa.JSON(), nullable=False),
    sa.Column('data_categories', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.String(length=200), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_data_consents_case_id'), 'model_data_consents', ['case_id'], unique=False)
    op.create_index(op.f('ix_model_data_consents_status'), 'model_data_consents', ['status'], unique=False)
    op.create_index(op.f('ix_model_data_consents_tenant_id'), 'model_data_consents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_data_consents_tenant_id'), table_name='model_data_consents')
    op.drop_index(op.f('ix_model_data_consents_status'), table_name='model_data_consents')
    op.drop_index(op.f('ix_model_data_consents_case_id'), table_name='model_data_consents')
    op.drop_table('model_data_consents')
    op.drop_index(op.f('ix_case_pseudonyms_tenant_id'), table_name='case_pseudonyms')
    op.drop_index(op.f('ix_case_pseudonyms_case_id'), table_name='case_pseudonyms')
    op.drop_table('case_pseudonyms')
    # ### end Alembic commands ###
