"""initial schema

Revision ID: fe52577cd05f
Revises:
Create Date: 2026-07-14 15:05:28.727960
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe52577cd05f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_table('case_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_files_owner_id'), 'case_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_case_files_tenant_id'), 'case_files', ['tenant_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_authorities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('article', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('effective_on', sa.Date(), nullable=False),
    sa.Column('expired_on', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=True),
    sa.Column('case_type', sa.String(length=80), nullable=False),
    sa.Column('court', sa.String(length=200), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('facts', sa.Text(), nullable=False),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('defenses', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('authority_refs', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_cases_content_hash'), 'legal_cases', ['content_hash'], unique=True)
    op.create_index(op.f('ix_legal_cases_source_url'), 'legal_cases', ['source_url'], unique=True)
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('agent', sa.String(length=80), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('protocol_version', sa.String(length=40), nullable=False),
    sa.Column('input_refs', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_agent'), 'agent_tasks', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_tasks_case_id'), 'agent_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('analysis_conclusions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('viewpoint', sa.Text(), nullable=False),
    sa.Column('counterargument', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('authority_ids', sa.JSON(), nullable=False),
    sa.Column('reasoning_trace', sa.JSON(), nullable=False),
    sa.Column('quality_metrics', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('invalidated_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_conclusions_case_id'), 'analysis_conclusions', ['case_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('holder', sa.String(length=100), nullable=False),
    sa.Column('authenticity', sa.String(length=30), nullable=False),
    sa.Column('gap', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_case_id'), 'evidence_items', ['case_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_case_id'), 'facts', ['case_id'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_case_id'), 'generated_documents', ['case_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_table('simulation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_sessions_case_id'), 'simulation_sessions', ['case_id'], unique=False)
    op.create_table('human_review_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_conclusions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['case_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_review_tasks_analysis_id'), 'human_review_tasks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_human_review_tasks_case_id'), 'human_review_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_human_review_tasks_status'), 'human_review_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_review_tasks_status'), table_name='human_review_tasks')
    op.drop_index(op.f('ix_human_review_tasks_case_id'), table_name='human_review_tasks')
    op.drop_index(op.f('ix_human_review_tasks_analysis_id'), table_name='human_review_tasks')
    op.drop_table('human_review_tasks')
    op.drop_index(op.f('ix_simulation_sessions_case_id'), table_name='simulation_sessions')
    op.drop_table('simulation_sessions')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_generated_documents_case_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_facts_case_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_evidence_items_case_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_analysis_conclusions_case_id'), table_name='analysis_conclusions')
    op.drop_table('analysis_conclusions')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_case_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_legal_cases_source_url'), table_name='legal_cases')
    op.drop_index(op.f('ix_legal_cases_content_hash'), table_name='legal_cases')
    op.drop_table('legal_cases')
    op.drop_table('legal_authorities')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_case_files_tenant_id'), table_name='case_files')
    op.drop_index(op.f('ix_case_files_owner_id'), table_name='case_files')
    op.drop_table('case_files')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
